# This workflow builds Android and ios sdk artefacts 
name: Build Artefacts

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  github-release:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v2

      - name: Use Node.js '16.x'
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - run: npm ci

      # Build Android Artifact
      - name: Generate Android artifacts using shell
        run: bash make-jar.sh

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11

      - name: Grant rights
        run: chmod +x java/build.gradle

      - name: Build jar
        working-directory: ./java
        run: gradle build

      # Build ios Artifact
      - name: Build JSON ABIs
        run: |-
          npm run build --if-present

      - name: Generate ABIs for iOS using shell script
        run: |
          mkdir ios
          npx ts-node make-ios.ts
