# This workflow builds Android and ios sdk artefacts
name: Build Artefacts

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js '16.x'
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - run: npm ci

      # Android artifacts
      - name: Install Web3j
        run: curl -L get.web3j.io | sh && source ~/.web3j/source.sh

      - name: Generate Android artifacts
        run: npx ts-node make-android.ts

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11

      - name: Grant rights
        run: chmod +x java/build.gradle

      - name: Build jar
        working-directory: ./java
        run: gradle build

      # iOS artifacts
      - name: Generate iOS artifacts
        run: |
          mkdir ios
          npx ts-node make-ios.ts
