# Upload Github artifacts

name: Upload Android Github artifacts CD

# Controls when the workflow will run
on:
  push:
    branches:
      - "main"

jobs:
  android-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check if version changed
        uses: EndBug/version-check@v1
        id: check

      - name: Use Node.js v16
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - if: steps.check.outputs.changed == 'true'
        run: npm ci

      - name: Install Web3j
        if: steps.check.outputs.changed == 'true'
        run: curl -L get.web3j.io | sh && source ~/.web3j/source.sh

      - name: Generate Android artifacts
        if: steps.check.outputs.changed == 'true'
        run: npx ts-node make-android.ts

      - name: Set up our JDK environment
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.11

      - name: Grant rights
        if: steps.check.outputs.changed == 'true'
        run: chmod +x java/build.gradle

      - name: Build jar
        if: steps.check.outputs.changed == 'true'
        working-directory: ./java
        run: gradle build

      - name: Publish jar
        if: steps.check.outputs.changed == 'true'
        working-directory: ./java
        run: gradle publish
        env:
          # https://github.com/actions/setup-node/issues/49
          # Have to use my personal access token until the issue is resolved
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.PERSONAL_ACTOR }}
