# This workflow build and publish NPM artifacts

name: Publish NPM artifacts

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  npm-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js '14.16.0'
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@lukso"
          cache: "npm"
      - run: git submodule update --init --recursive
      - run: npm ci
      - run: cd ./submodules/ERC725/implementations && npm install
      - run: npx hardhat compile
      - run: npm run test
      - run: npm run package
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
