name: Solhint CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: solhint
        uses: contractshark/inject-solhint-ci@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # reporter: github-pr-review # Change reporter.
          solhint_input: "contracts/**/*.sol"
